dashpay/grovedb

.gitignore, .rustfmt.toml, grovedb/Cargo.toml, grovedb/src/lib.rs, grovedb/src/subtree.rs, merk/src/merk/mod.rs
This is an attempt to implement simple insert and get operations for GroveDb (inside subtrees without exposing to public API yet) to store binary data
=> feat: subtree get/insert

Cargo.toml, grovedb/Cargo.toml, grovedb/src/lib.rs, grovedb/src/subtree.rs, merk/Cargo.toml, merk/src/lib.rs, merk/src/merk/chunks.rs, merk/src/merk/mod.rs, merk/src/proofs/chunk.rs, merk/src/proofs/query/mod.rs, merk/src/test_utils/crash_merk.rs, merk/src/test_utils/mod.rs, merk/src/test_utils/temp_merk.rs, merk/src/tree/encoding.rs, merk/src/tree/mod.rs, merk/src/tree/ops.rs, merk/src/tree/walk/mod.rs, merk/src/tree/walk/ref_walker.rs, storage/Cargo.toml, storage/src/lib.rs, storage/src/rocksdb_storage.rs
This PR includes abstracting from RocksDB as well as making Merk unaware of prefixes and other details.
GroveDB chooses the storage, but that could be also moved out to the caller site later if needed.
=> feat: abstract Merk storage

grovedb/src/lib.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/Cargo.toml, merk/src/lib.rs, merk/src/merk/chunks.rs, merk/src/merk/mod.rs, merk/src/proofs/chunk.rs, merk/src/proofs/encoding.rs, merk/src/proofs/query/map.rs, merk/src/proofs/query/mod.rs, merk/src/proofs/tree.rs, merk/src/test_utils/crash_merk.rs, merk/src/test_utils/temp_merk.rs, merk/src/tree/commit.rs, merk/src/tree/encoding.rs, merk/src/tree/link.rs, merk/src/tree/mod.rs, merk/src/tree/ops.rs, merk/src/tree/walk/fetch.rs, merk/src/tree/walk/mod.rs, merk/src/tree/walk/ref_walker.rs, node-grove/src/converter.rs, node-grove/src/lib.rs, storage/Cargo.toml, storage/src/rocksdb_storage.rs
This PR adds an ability to make a checkpoint of current GroveDB state, basically by reusing RocksDB checkpointing funcitonality;
Also there is an attempt to deprecate `failure` crate and to do a little cleanup of error handling story
=> feat: Simple checkpoint

grovedb/src/lib.rs, grovedb/src/tests.rs
Insert an element at a path only if that path is empty
=> feat: insert if not exists

grovedb/src/lib.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/merk/mod.rs, storage/src/rocksdb_storage.rs
This PR contains two changes:
It alters how path compression works, previously collisions may occur for cases like `[a, ab] vs [aa, b]`, also subtree keys shared the same prefix as parent trees which is harmful for iteration over subtree elements as there is no way to find out where to stop, now they're not.
New path compression algorithm (for subtree key):
1. Concat all path segments as before
2. Append number of segments
3. Append lengths of each segment
4. hash it
Subtree elements' keys use the same approach, but appending their key after hashing happened, this way their order is preserved and they're located sequentially in DB.
This allows for a given subtree to iterate over key-value pairs sorted by key, values are `Element` object
=> feat: subtree pairs iterator

grovedb/src/lib.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/merk/mod.rs, storage/src/lib.rs, storage/src/rocksdb_storage.rs
This PR improves GroveDB's API with `delete` method.
Currently it supports two scenarios:
1. Delete a subtree item (scalar/reference)
2. Delete a subtree, this recursively deletes all subtrees of a subtree too, currently it requires full traversal
Note that references on deleted object will stay and become invalid
=> feat: delete operation for elements and trees

grovedb/src/lib.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
This PR adds `get_query` method which adds an ability to get elements from GroveDB using same `PathQuery` as used for proof generation.
Current implementation uses raw iterator.
=> add `get_query` method

grovedb/src/lib.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, grovedb/src/transaction.rs, merk/Cargo.toml, merk/src/merk/chunks.rs, merk/src/merk/mod.rs, merk/src/proofs/chunk.rs, merk/src/test_utils/crash_merk.rs, merk/src/test_utils/temp_merk.rs, merk/src/tree/kv.rs, merk/src/tree/link.rs, merk/src/tree/mod.rs, merk/src/tree/ops.rs, node-grove/src/lib.rs, storage/Cargo.toml, storage/src/lib.rs, storage/src/rocksdb_storage.rs, storage/src/rocksdb_storage/batch.rs, storage/src/rocksdb_storage/mod.rs, storage/src/rocksdb_storage/storage.rs, storage/src/rocksdb_storage/transaction.rs
The logic of `Merk::clear` is not compatible with transactions really - something had to be redone.
Merk::clear consumes itself. It also creates a batch. With transactions, the batch is either Batch or Transaction. But transaction borrows storage, and thus compiler thinks that storage lives less than the transaction.
All tests are passing, except the ones that delete subtrees. That’s because I’ve commented out `Merk::clear` method as explained above. 
I’ve also left a pretty self-explanatory doc comment on `GroveDB::start_transaction`. Run `cargo doc --open` to check it out.  Please take a look at it! It is a bit ugly, but it works!
Happy new year! :clinking_glasses:
=> feat: transactions

grovedb/src/lib.rs, grovedb/src/tests.rs
Implement `is_transaction_started` method to check if transaction is already started or not
=> feat: `is_transaction_started` method

grovedb/src/lib.rs, grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
this PR adds `root_hash` method for GroveDb with respect to transactions
=> feat: add `root_hash` method

grovedb/src/tests.rs
check that abort_transaction does what we expect it should (based on the code)
=> test: better check the results of abort_transaction

grovedb/src/lib.rs, merk/src/proofs/query/mod.rs, merk/src/proofs/tree.rs, merk/src/test_utils/mod.rs, merk/src/tree/iter.rs, merk/src/tree/kv.rs, merk/src/tree/link.rs, merk/src/tree/mod.rs
When a function can be const, it probably should be const. This way it can be called at compile time, and it makes it clear to the caller that nothing on the heap is being touched.
=> refactor: mark a number of functions as const

grovedb/src/lib.rs, grovedb/src/tests.rs
At some moment we stopped to persist root leaves data in a storage that's why on GroveDB reopening we cannot get an appropriate root hash or to print any info deeper than just "root"
=> fix: persist root leaves data

grovedb/src/lib.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/operations/is_empty_tree.rs, grovedb/src/subtree.rs, grovedb/src/subtrees.rs, grovedb/src/tests.rs, grovedb/src/visualize.rs
This PR simplifies subtrees usage returning a kind of a pointer to Merk when accessing data (temporary or not), so no need to insert it back;
Note that as it uses `RefCell` internally multiple sequential accesses to subtrees without dropping previous borrows will cause a panic, to simplify "oneshot" usage of a subtree there is an `apply` helper
Built prefix if presents could be accessed with `get_prefix`
=> fix: do not remove subtree from temp_subtrees

grovedb/src/lib.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/subtrees.rs, grovedb/src/tests.rs
This PR decomposes path errors into 4 categories.
InvalidPath : the path is not valid/does not exist, and it represents a logical error by the client.
PathNotFound: the path does not exist, but it doesn't represent a logical error by the client. Meaning that the query was valid, but an intermediate path was just not present.
PathKeyNotFound: the path was found, but the key was not, the query was valid but there was nothing there.
CorruptedPath : GroveDB internal error, not a logical error by the client.
=> feat: better path errors

grovedb/src/lib.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, grovedb/src/util.rs, grovedb/src/visualize.rs, merk/src/merk/chunks.rs, merk/src/merk/mod.rs, merk/src/test_utils/crash_merk.rs, merk/src/test_utils/temp_merk.rs, storage/src/rocksdb_storage/storage.rs, storage/src/rocksdb_storage/tests.rs, storage/src/storage.rs
PR to keep progress of storage abstraction task, currently cannot be finished easily without GATs
=> refactor: move get_context methods to trait

grovedb/Cargo.toml, grovedb/benches/insertion_benchmark.rs, grovedb/src/tests.rs
Adds some benchmarks for insertion;
Comparing to `master` version, new storage approach works faster for non-transactional insertions (~12% for scalars, ~150% for root leafs, ~70% for nested insertions), and ~20% slower (except root tree bench) in transactions (as there is no temp trees and everything goes to rocksdb directly)
=> feat: add benchmark for insertion

merk/src/proofs/query/mod.rs
Merk currently supports proofs for:
- key
- range
- range_inclusive
This pr adds:
- range_to
- range_to_inclusive
- range_from
- range_after
- range_after_to
- range_after_to_inclusive
- range_full
=> feat: addition of more range types

grovedb/Cargo.toml, grovedb/src/subtree.rs
This reduces the serialization size of an element.
It also attempts to add methods to figure out the disk space footprint of an element.
=> feat: var int serialization

storage/src/lib.rs, storage/src/rocksdb_storage.rs, storage/src/rocksdb_storage/storage.rs, storage/src/rocksdb_storage/storage_context.rs, storage/src/rocksdb_storage/storage_context/batch.rs, storage/src/rocksdb_storage/storage_context/context_batch_no_tx.rs, storage/src/rocksdb_storage/storage_context/context_batch_tx.rs, storage/src/rocksdb_storage/storage_context/context_tx.rs, storage/src/rocksdb_storage/storage_context/raw_iterator.rs, storage/src/rocksdb_storage/test_utils.rs, storage/src/rocksdb_storage/tests.rs, storage/src/storage.rs
This PR adds two storage contexts: one for cross-subtrees batches and another to do it inside transactions.
Note: while this adds a technical ability to apply changes to multiple subtrees in a single pass it's still not integrated with GroveDB
=> feat(storage): multi-context batches

merk/src/proofs/query/mod.rs
separated proof verification logic from root hash verification, 
sometimes you don't know the expected root hash at the time of verification.
=> feat: refactor merk proof verification interface

grovedb/src/lib.rs, grovedb/src/operations.rs, grovedb/src/operations/proof.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/lib.rs, merk/src/merk/mod.rs, merk/src/proofs/query/mod.rs, merk/src/tree/kv.rs, merk/src/tree/mod.rs
The verify_query function must be called with the same limit and offset values
that was used during proof construction. (anything different and verification
fails).
Grovedb proof_construction chains multiple merk proofs.
To verify a chain, we need to know the output of the previous
verification i.e (remaining limit and offset values)
This pr allows the verification function to return the net limit and offset value
=> feat: propagate remaining limit and offset after verification

Cargo.toml, grovedb/Cargo.toml, grovedb/benches/insertion_benchmark.rs, grovedb/src/batch.rs, grovedb/src/lib.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, grovedb/src/visualize.rs, merk/src/merk/chunks.rs, merk/src/merk/mod.rs, merk/src/tree/encoding.rs, storage/Cargo.toml, storage/src/rocksdb_storage/storage_context/batch.rs, storage/src/rocksdb_storage/storage_context/context_batch_no_tx.rs, storage/src/rocksdb_storage/storage_context/context_batch_tx.rs, storage/src/rocksdb_storage/storage_context/context_no_tx.rs, storage/src/rocksdb_storage/storage_context/context_tx.rs, storage/src/rocksdb_storage/tests.rs, storage/src/storage.rs, visualize/Cargo.toml, visualize/src/lib.rs
This PR improves GroveDB API to support batched updates.
Batches could be used to perform multiple operations on GroveDB and as a result to have exactly one database (RocksDB in our case) batch, moreover, this implies atomicity and invalid operations will fail the whole batch with no partially applied state with no need of transaction (transactions are supported as well for multiple batches if needed).
This is achieved in a number of steps:
1. GroveDB batch should pass validation, this requires to perform some `get` requests to GroveDB to ensure that insertions are done to existing subtrees if there is no way to check that they will be inserted within the same batch, also tree deletions and overwrites must be deleted recursively, that requires to do even more `get`s, but still no writes; …
=> feat: GroveDB batch operations

grovedb/src/operations/delete.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/operations/is_empty_tree.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/tests.rs
It wasn't very clear what `key` argument should do so it was removed, also fixed a bug when this function could report no errors if an item under a path exists, but it's not a tree
=> fix: simplify `check_subtree_exists`

grovedb/src/batch.rs, grovedb/src/lib.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, grovedb/src/visualize.rs, node-grove/src/converter.rs
API consumers can add an optional one-byte flag (meta-data) to elements on insertion.
Updated the element instantiation interface, and created separate methods for creating elements with and without flags.
=> feat: element flags

grovedb/src/batch.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/util.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/tests.rs, node-grove/src/lib.rs
It is possible that a path query points to a subtree that exists but is empty.
Before this pr, proof generation panics at that point as it can't apply the given query to the empty subtree.
This pr adds a marker to the generated proof to signify this case.
- Verification returns an empty root hash [0; 32] when this marker is hit (allowing for further verification).
=> fix: handle path pointing to empty tree case

grovedb/src/batch.rs, grovedb/src/subtree.rs, merk/src/merk/mod.rs
This PR makes `BatchStructure` generic over trees cache rather than storage, thus `get_merk_fn` is hidden in cache implementation and occurs only in places where it needs to be and this ends up in better separation of two cache implementations (and according code paths)
TODO: switch on develop after feat/worstCaseFees got merged
=> Batch worst case fees typelevel fixes

grovedb/src/batch.rs, grovedb/src/lib.rs, grovedb/src/subtree.rs, merk/src/tree/kv.rs, merk/src/tree/mod.rs, merk/src/tree/ops.rs, merk/src/tree/walk/mod.rs
This reverses the use of the index map and batches having the same execution order as non batches, but allows for Merk batches.
=> feat: merk batches

grovedb/src/query.rs, merk/src/proofs/query/mod.rs
Restricts mergeable path queries to those with unique and none subset paths.
Also refactors the merge algorithm to better describe what's going on.
=> feat: restrict complete subset paths when merging path queries

grovedb/src/lib.rs, grovedb/src/operations/get.rs, grovedb/src/query.rs, grovedb/src/query_result_type.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/merk/mod.rs, node-grove/src/lib.rs
Sometimes on a query we are interested in the value, sometimes the key value, and even some other times the path key and the value. This PR allows us to specify the return type of items.
=> feat: query return different types of results

merk/src/tree/kv.rs
When creating or updating a kv node, the value hash is computed twice. This PR removes the unnecessary extra hashing step.
=> optimisation: unnecessary hashing

grovedb/src/query.rs, merk/src/proofs/query/mod.rs
Before merging equal paths, check that none of their path queries has a subquery (this prevents unequal and non-unique path query concealment).
=> check for subquery with equal path merge

grovedb/src/batch.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/query.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, grovedb/src/visualize.rs, merk/src/merk/mod.rs, merk/src/tree/mod.rs, merk/src/tree/ops.rs, node-grove/src/converter.rs
For non-batch insert reference 
- Single get call and no node hashing
For batch insert reference
- Clients can specify application-specific max reference hop (allowing worst-case cost to be closer to actual cost)
=> perf: insert reference optimization for worst case

merk/src/merk/mod.rs, merk/src/merk/restore.rs, merk/src/tree/encoding.rs
Decoding operation would panic if input bytes are invalid, this handles such cases.
=> feat: return result during tree decode

costs/src/lib.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/merk/mod.rs, merk/src/tree/commit.rs, merk/src/tree/encoding.rs, merk/src/tree/mod.rs, storage/src/rocksdb_storage/storage_context/batch.rs
For better cost UX, written storage cost should be split into added_storage, replaced_storage and removed_storage
where replaced_storage is much less than added_storage.
This PR modifies merk to return the information needed to compute the added, replaced and removed storage
=> feat: populate key value storage cost

grovedb/src/batch.rs
We had the batch operation consistency checker, but it wasn't used. Enabled it and added tests for verify it's correctness.
=> fix: batch operation consistency check

grovedb/Cargo.toml, grovedb/src/batch/mod.rs, grovedb/src/element/get.rs, grovedb/src/element/insert.rs, grovedb/src/element/query.rs, grovedb/src/estimated_costs/average_case_costs.rs, grovedb/src/estimated_costs/worst_case_costs.rs, grovedb/src/lib.rs, grovedb/src/operations/get/mod.rs, grovedb/src/operations/get/query.rs, grovedb/src/operations/insert/mod.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/tests/mod.rs, grovedb/src/tests/sum_tree_tests.rs, grovedb/src/tests/tree_hashes_tests.rs, merk/Cargo.toml, merk/src/merk/mod.rs, merk/src/test_utils/crash_merk.rs, node-grove/Cargo.toml
There was a small issue inconsistency issue in rs-drive where we were not getting the same cost value for getting a contract, and I realized this was due to caching. Since we always need that value to be deterministic even outside of transactions it made sense to offer a way to get directly without cache.
=> feat: added option to get from grovedb without using cache

grovedb/src/batch/single_insert_cost_tests.rs, grovedb/src/element/get.rs, grovedb/src/operations/insert/mod.rs, merk/src/tree/kv.rs
Costs for loading bytes from storage included costs that were not dependent on the node itself.
This change allows for fetches to consistently return the same result as long as the item has not changed.
=> feat: deterministic loaded bytes from storage

grovedb/src/element/query.rs, grovedb/src/lib.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/util.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/replication.rs, grovedb/src/tests/common.rs, grovedb/src/tests/mod.rs, grovedb/src/tests/query_tests.rs, grovedb/src/tests/sum_tree_tests.rs, grovedb/src/tests/tree_hashes_tests.rs, merk/src/merk/mod.rs, merk/src/proofs/query/mod.rs, merk/src/tree/kv.rs
Allow proofs to add elements from different tree levels to the result set.
If an element encountered through a query, has no subquery value (default or conditional) and no subquery path (translation), it gets added to the result set. 
We achieve this by reducing the limit offset values deterministically, across both proof generation and verification.
Added unit tests. 
=> feat: mixed tree level proofs

grovedb/src/operations/proof/generate.rs, grovedb/src/tests/query_tests.rs
Prior to this pr, generating proofs with a limit of zero failed during verification. 
This was because proof construction didn't generate a root hash proof for the subtree at the given path when the limit is zero.
Generate root hash proof for subtree at the given path when the limit is 0.
Unit tests.
=> fix: limit zero proof bug

grovedb/src/operations/proof/verify.rs, grovedb/src/tests/query_tests.rs, merk/src/proofs/query/verify.rs
Add verification function to generate absence result alongside the result set. 
Works for only a subset of path queries, and will have to be upgraded (v2) to work for all possible path queries. 
- Added a new verification method for this feature
- Check terminal keys constraints
- Generate terminal keys
- Build a new result set from a combination of terminal keys and the old result set
Unit tests (for the simple case)
Nope (additive)
=> feat: absence proof v1

grovedb/src/batch/batch_structure.rs, grovedb/src/batch/just_in_time_cost_tests.rs, grovedb/src/batch/mod.rs, grovedb/src/batch/options.rs, storage/src/rocksdb_storage.rs, storage/src/rocksdb_storage/storage.rs, storage/src/storage.rs
In RS-Drive atomicity of state transitions is paramount. A state transition is a collection of multiple operations that often will cause one or more identity balances to change. The amount that the identity balance must change by is driven by costs of changes in the batch. Ideally we should be able to alter the batch by adding operations based on calculated information coming from the batch itself.
For example in one batch have the document insertion, but also the reduction of credits of the identity due to the document insertion.
To be able to perform this feature, we need to get back costs from an insertion, then perform just in time updates to the batch, this is what is coded up in this PR.
Added some unit tests
No breaking changes
=> feat: partial batches

grovedb/Cargo.toml, grovedb/src/element/helpers.rs, grovedb/src/element/mod.rs, grovedb/src/error.rs, grovedb/src/lib.rs, merk/Cargo.toml, merk/src/error.rs, merk/src/estimated_costs/mod.rs, merk/src/lib.rs, merk/src/proofs/query/query_item/mod.rs, merk/src/proofs/query/verify.rs, merk/src/tree/mod.rs
Noticed we build librocksdb-sys when building the verify feature for merk and grovedb, this should not be the case.
Got rid of the dependency
Tests pass + verification feature builds
=> feat: don't build librocksdb for verify feature

grovedb/src/batch/batch_structure.rs, grovedb/src/batch/estimated_costs/average_case_costs.rs, grovedb/src/batch/estimated_costs/worst_case_costs.rs, grovedb/src/batch/mod.rs, grovedb/src/element/query.rs
We hereby give the ability to refresh a unidirectional reference. This is needed every time the element that is being pointed to changes. Using unidirectional references is not safe in the context of grovedb, however it is much more efficient. Projects that choose to use unidirectional references need to do so safely.
We added the ability to refresh a unidirectional reference.
Added a test in the platform project.
=> feat: refresh unidirectional reference

grovedb/src/operations/proof/generate.rs, grovedb/src/tests/query_tests.rs, storage/src/rocksdb_storage/storage_context/raw_iterator.rs
Cost values depended on the ordering of key values in the rocksdb storage layer, leading to different state roots when prefix computation changes. 
Unified the costs, regardless of the ordering in the underlying storage layer. 
- if the next key is from another merk, rather than add the cost of the key we add the max key length
- if the next key is none, add the max key length rather than nothing. 
=> fix: non deterministic cost

grovedb/src/lib.rs, storage/src/lib.rs, storage/src/rocksdb_storage/storage.rs, storage/src/rocksdb_storage/storage_context.rs, storage/src/rocksdb_storage/storage_context/batch.rs, storage/src/rocksdb_storage/storage_context/context_batch_no_tx.rs, storage/src/rocksdb_storage/storage_context/context_batch_tx.rs, storage/src/rocksdb_storage/storage_context/context_no_tx.rs, storage/src/rocksdb_storage/storage_context/context_tx.rs, storage/src/rocksdb_storage/storage_context/raw_iterator.rs, storage/src/storage.rs
Before we agree on GroveDB's public API there are things that are obviously must not be a part of it.
1. Storage details are gone from public exports; also this PR addresses other visibility issues found during debugging
2. `build_prefix` now returns more specific type as we agreed on 
With GroveDB and Drive's test suites
=> fix: hide storage api

grovedb/src/lib.rs, grovedb/src/tests/mod.rs, storage/src/rocksdb_storage/storage.rs
Clear GroveDB data by deleting each key value pair in the rocksdb column families. 
This is not efficient and should be revised, a constant time solution is desired. 
=> feat: raw iter data wipe

grovedb/src/operations/proof/verify.rs
During proof verification, we added the last key to the current path before completing subquery path proof verification. This made the absence function not work as expected due to incorrect paths. 
=> fix: result set path error

merk/src/tree/ops.rs
Merk deletion is highly recursive, in this PR we remove some recursion and clean up some stack values.
Ran tests, and also ran against drive.
None
=> fix: improving merk deletion

grovedb/src/error.rs, grovedb/src/operations/delete/mod.rs
Add method to clear a subtree, preserving the parent Element::Tree (setting the root_key = None)
If the merk tree has nested trees, those trees are deleted also.
=> feat: clear subtree

grovedb/src/batch/key_info.rs, grovedb/src/batch/mod.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/util.rs
When doing proof generation, we sometimes reduce the limit and offset value to save space for some element we know we'd be generating a proof for in the future. 
During proof generation for that element, we are supposed to add back this saved space, we failed to do this, leading to a bug. 
This PR fixes this. 
=> fix: early limit reduction

grovedb/src/element/query.rs, grovedb/src/operations/get/query.rs, grovedb/src/query/mod.rs, grovedb/src/reference_path.rs, grovedb/src/tests/mod.rs, grovedb/src/tests/query_tests.rs, node-grove/src/lib.rs
When Querying Grovedb using subqueries and with a limit the limit would only decrease if the subquery actually had an item. However in most cases the limit is there to protect against very expensive queries.
The queries would be expensive because we could go through many many trees where the sub elements have no matches, hence the limit would not decrease and hence we would continue on the increasingly expensive query.
Created an option to allow to decrease the limit by one per iteration if subqueries have no items on them.
Updated tests and debugged to make sure it was working
=> fix!: limit will now decrease when subquery has no elements

costs/Cargo.toml, grovedb/Cargo.toml, grovedb/src/error.rs, grovedb/src/operations/delete/mod.rs, grovedb/src/operations/get/query.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/query/mod.rs, merk/src/error.rs, merk/src/proofs/query/mod.rs, storage/Cargo.toml
=> refactor: changed some str to Strings for better errors

grovedb/src/element/mod.rs, grovedb/src/element/query.rs, grovedb/src/operations/get/query.rs, grovedb/src/query/mod.rs, grovedb/src/reference_path.rs, grovedb/src/tests/mod.rs, grovedb/src/tests/query_tests.rs, merk/src/proofs/query/mod.rs, node-grove/src/lib.rs
If a tree on an intermediate path on a subquery path was not present we would receive an error. Now instead we have a field to allow this situation or not. If the option is set to false (don't error), then we simply don't error, any query for any item in that path will simply give back a None value.
Also we fixed an issue with terminal paths.
Added a test to verify this works as intended.
Breaking in the sense that method calls have changed.
=> fix!: empty parent paths should only error if we want them to error

grovedb/src/replication.rs, tutorials/src/bin/replication.rs
State sync wasn't versioned. This needs to be addressed as state sync protocol will probably be upgraded in the future.
Added `version` field in all state sync APIs.
Now, only `CURRENT_STATE_SYNC_VERSION` (=1) is supported. Any other version will be rejected.
=> feat: added version in state sync

grovedb/src/replication.rs, tutorials/src/bin/replication.rs
Until now, state syncing was made one subtree at a time sequentially. This has an room for optimization. 
Each time a new subtree is synced, grovedb discovers any new subtrees that can be synced and starts fetching for them in parallel.
no
=> feat: sync multiple subtrees

grovedb/src/replication.rs, merk/src/proofs/encoding.rs
Platform ABCI isn't aware of Ops structure. Therefore, grovedb state sync related APIs should always use encoded into bytes ops.
Wrote utility functions `util_encode_vec_ops` and `util_decode_vec_ops` and adjusted `fetch_chunk` and `apply_chunk`.
=> feat: State sync APIs should use encoded Ops

grovedb/src/replication.rs, tutorials/src/bin/replication.rs
Constructors for `SubtreeStateSyncInfo` and `MultiStateSyncInfo` were depended on a ref of grovedb.
Simplified this by using default new() approach
=> refactor: correct constructors for `SubtreeStateSyncInfo` and `MultiStateSyncInfo`

grovedb/src/replication.rs, tutorials/src/bin/replication.rs
- Root chunk id is expected to be equal to `app_hash` instead of `null_hash` (This facilitates Tenderdash in state sync init phase)
- Changed API of `appy_chunk` to accept separately parameters and not in tuple (better clarity)
Updated tutorial `replication`
=> refactor: root `chunk_id` should be equal to `app_hash`

grovedb/src/debugger.rs, grovedb/src/lib.rs
=> receive full address for visualizer

merk/src/proofs/query/query_item/mod.rs
This is a critical fix for query item range inclusive.
If they were being queried in descending order they would add an extra value that was out of bounds.
=> fix: query item range inclusive

grovedb/build.rs
=> better trunk panic

grovedb/build.rs
=> Grovedbg build fix

grovedb/Cargo.toml, grovedbg-types/Cargo.toml
grovedbg-types crate required for GroveDBG capabilities shall be published to crates.io like any other part of GroveDB
=> chore: set grovedbg-types version

grovedb/src/debugger.rs, grovedb/src/operations/proof/generate.rs, grovedbg-types/Cargo.toml, grovedbg-types/src/lib.rs, merk/src/debugger.rs, merk/src/tree/kv.rs
GroveDBG protocol was updated to allow visualizer to do queries and receive proofs.
`grovedbg-types` update, extended GroveDBG http server
=> feat: queries proofs grovedbg update

.gitmodules, grovedb/build.rs
New version of Visualizer is now capable of executing queries and expect returned proofs. This PR updates the Visualizer version.
Update Visualizer version.
Also deleted submodule as no longer needed since we use prebuilt artifact of Visualizer
For the build script the link was updated with according checksum.
Tested locally with a user application with grovedb dependency set to this branch.
=> bump grovedbg version

costs/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedbg-types/Cargo.toml, merk/Cargo.toml, node-grove/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, visualize/Cargo.toml
Update rc.2 to 1.0.0 at crates' manifests
=> chore: update versions to 1.0.0

.gitmodules, README.md, costs/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedb/build.rs, grovedb/src/debugger.rs, grovedb/src/element/mod.rs, grovedb/src/operations/proof/generate.rs, grovedbg-types/Cargo.toml, grovedbg-types/src/lib.rs, merk/Cargo.toml, merk/src/debugger.rs, merk/src/tree/kv.rs, node-grove/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, visualize/Cargo.toml
=> chore: merge v1.0.0 into master

grovedb/src/element/mod.rs, grovedb/src/lib.rs, grovedb/src/operations/insert/mod.rs, grovedb/src/tests/mod.rs
This PR addresses an issue with references insertion outside of a batch, also fixes verify function to align it all with batches and proof system
Combined hash of references now uses value hash of the last item of references chain instead of the value hash of the direct item, which in turn could be a reference
add tests for longer reference chains both for batch insertions and regular ones
=> fix: reference insertion without batch + verify

grovedb/build.rs, grovedb/src/query/mod.rs, merk/src/proofs/query/mod.rs
PathQuery depth is a small feature that gives the max depth of the PathQuery. This can be used to estimate the complexity of the PathQuery
The PathQuery depth taxes the max of default pathquery subbranches and conditional pathquery subbranches.
Added a test to check if it worked.
None
=> feat: PathQuery depth

grovedb/src/query/mod.rs, merk/Cargo.toml, merk/src/proofs/query/mod.rs, merk/src/proofs/query/query_item/mod.rs
PathQuery didn't have a serialization, making it more difficult to transport or to store.
Added bincode serialization/deserialization to PathQuery.
Added unit tests.
=> feat: Path Query Bincode Serialization

costs/src/lib.rs, grovedb/src/element/get.rs, grovedb/src/estimated_costs/average_case_costs.rs, grovedb/src/estimated_costs/worst_case_costs.rs, merk/src/estimated_costs/average_case_costs.rs, merk/src/estimated_costs/worst_case_costs.rs, merk/src/merk/defaults.rs, storage/src/rocksdb_storage/storage.rs, storage/src/rocksdb_storage/storage_context/context_no_tx.rs, storage/src/rocksdb_storage/storage_context/context_tx.rs, storage/src/rocksdb_storage/storage_context/raw_iterator.rs
This PR updates some of the fields of accumulated costs data type
Changed datatypes used
`seek_count`: `u16 -> u32`
`storage_loaded_bytes`: `u32 -> u64`
=> fix: update seek count and loaded bytes sizes

README.md, grovedb/Cargo.toml, grovedb/build.rs, grovedb/src/debugger.rs, grovedbg-types/src/lib.rs
Add support for GroveDBG sessions and update served GroveDBG app version to the latest release.
Update GroveDBG protocol fetch and query requests with mandatory session identifier to maintain consistency between multiple requests. Sessions are achieved by using temporary GroveDB snapshots.
Manually
Previous GroveDBG installations (in case of native apps) won't work with this version.
=> GroveDBG v1.1.0

costs/Cargo.toml, grovedb-epoch-based-storage-flags/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedbg-types/Cargo.toml, merk/Cargo.toml, node-grove/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, tutorials/Cargo.toml, visualize/Cargo.toml
Preparing for a new GroveDB release.
Updated minor version; organized dependencies in sections to group grovedb* crates visually
=> chore: bump crate versions

grovedb-epoch-based-storage-flags/src/lib.rs
There was an issue in documents purchase state transition that showed this error in GroveDB.
Used old ownerId in removed bytes instead of merged one.
Verified fix works
Should never have worked, hence no issue.
=> fix: merging epoch removed bytes should use old owner id instead of merged one

grovedb/src/element/get.rs, grovedb/src/element/query.rs
=> fix: fixed issue with query if no path element

grovedb/src/lib.rs
Added the export of `TreeFeatureType` from `grovedb_merk::tree` when the "minimal" or "verify" features are enabled. This change allows users to access `TreeFeatureType` in configurations that require these features, enhancing the functionality and flexibility of the library.
=> feat: add TreeFeatureType export for minimal and verify features

grovedb/src/lib.rs
Added `VerifyOptions` to the `grovedb_merk::proofs::query` module. This change allows for enhanced verification options when querying proofs, improving flexibility and functionality for users requiring verification features.
=> feat: add VerifyOptions to proofs module

grovedb/src/lib.rs, grovedb/src/operations/proof/verify.rs
Updated the proof verification logic in the `GroveDb` implementation. The changes ensure that when a query item is not found at a specified path, the system correctly processes the path and updates the result accordingly to return a tree item as that is what we are looking for. This addresses potential issues with proof validation, specifically in scenarios where the expected tree structure does not match the provided proof. The logic for handling limits on query results has also been refined to prevent premature termination of the verification process.
=> fix: correct proof verification logic in GroveDb
