dashpay/grovedb

grovedb/src/operations/aux.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
This PR adds optional transactions for *_aux family of GroveDB methods
=> feat: transactions support for aux methods

grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
Contains implementation for 
- range_after
- range_after_to
- range_after_to_inclusive
=> feat: range after items

grovedb/src/lib.rs, grovedb/src/tests.rs
- Introduced `rollback_transaction` method to rollback a transaction.
- Cleanup temp tree after transaction commitment
=> feat: transaction rollback

grovedb/src/lib.rs, grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
Allow to abort the transaction and reset transactional data
=> feat: `abort_transaction` method

grovedb/src/lib.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
There were some big issues in iterators, this should fix them.
=> fix: iteration

grovedb/Cargo.toml, grovedb/src/lib.rs, grovedb/src/operations/get.rs, grovedb/src/operations/proof.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/proofs/query/mod.rs
This allows for recursively applying queries to tree elements returned by parent queries.
=> feat: recursive subqueries

.github/workflows/release.yml
Fix the release workflow issue https://github.com/dashevo/grovedb/runs/4964028991?check_suite_focus=true#step:8:90
=> ci: make NPM package public

grovedb/src/lib.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/merk/mod.rs, merk/src/proofs/chunk.rs, merk/src/proofs/query/mod.rs, merk/src/proofs/tree.rs, merk/src/tree/encoding.rs, merk/src/tree/ops.rs, storage/src/lib.rs, storage/src/rocksdb_storage/batch.rs, storage/src/rocksdb_storage/mod.rs, storage/src/rocksdb_storage/storage.rs
This PR fixes all remaining warnings including clippy lints (even for tests)
=> fix more warnings with lints

.cargo/config.toml, .github/workflows/release.yml, node-grove/docker/build-aarch64-unknown-linux-musl.sh, package.json
Include arm64 musl prebuild for alpine docker images
=> ci(release): build binding for arm64 musl

grovedb/src/lib.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/is_empty_tree.rs, grovedb/src/subtree.rs, grovedb/src/subtrees.rs, grovedb/src/tests.rs, merk/src/merk/chunks.rs, merk/src/merk/mod.rs, merk/src/proofs/chunk.rs, storage/src/lib.rs, storage/src/rocksdb_storage/mod.rs, storage/src/rocksdb_storage/storage.rs
This PR allows to create raw iterator with transaction and fixes subtrees deletion with transactions
=> fix: bugfix for a transactional raw iter

merk/src/proofs/query/mod.rs, storage/src/lib.rs, storage/src/rocksdb_storage/mod.rs
This should do what we are trying to achieve, just more efficiently.
=> perf: seek_for_prev optimization

grovedb/src/subtree.rs, merk/Cargo.toml, merk/src/lib.rs, merk/src/proofs/encoding.rs, merk/src/proofs/query/map.rs, merk/src/tree/kv.rs, merk/src/tree/mod.rs
These changes allow us to use stable Rust compiler on GroveDB
=> refactor: stable rust

merk/src/proofs/query/mod.rs
Guess this had been forgotten :(
=> fix: added a limit to range to inclusive

grovedb/src/lib.rs, grovedb/src/operations/proof.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/lib.rs, merk/src/merk/mod.rs, merk/src/proofs/query/mod.rs
returns the final limit and offset values after proof construction
=> feat: propagate remaining limit and offset after proof construction

grovedb/src/batch.rs
=> Revert "fix: made some fields public of groveDB Op public"

grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/util.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/tests.rs
This pr proves the absence of a path that doesn't point to a subtree.
=> feat: prove path absence

grovedb/src/operations/get.rs, grovedb/src/subtree.rs
This allows to query trees themselves.
=> feat: raw path queries

grovedb/src/query.rs
Merging equal subqueries is not allowed for some reason. I didn't find any reason for that. Waiting for @iammadab to discuss.
=> fix: merging equal path queries

grovedb/src/batch.rs, grovedb/src/replication.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, merk/src/merk/mod.rs
One seek for getting the merk tree of the root, and one seek for insertion.
=> test: batch insert to root should be two seeks

grovedb/src/batch.rs, grovedb/src/lib.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/reference_path.rs, grovedb/src/subtree.rs, grovedb/src/tests.rs, grovedb/src/visualize.rs, node-grove/src/converter.rs
This PR allows for different reference type variants.
Allows users chose the variant that provides the highest storage efficiency for their specific scenario.
=> feat: efficient references

grovedb/src/reference_path.rs
Reference variant to point to a sibling.
=> feat: sibiling reference

grovedb/benches/insertion_benchmark.rs, grovedb/src/query.rs, merk/Cargo.toml, merk/benches/merk.rs, merk/benches/ops.rs
Apparently they were broken and required nightly
=> fix: Merk benchmarks

grovedb/src/tests.rs
Add test to check hardcoded proof size.
=> test: proof size

costs/src/lib.rs, costs/src/storage_cost/mod.rs, grovedb/src/batch/mod.rs, grovedb/src/batch/single_deletion_cost_tests.rs, grovedb/src/batch/single_insert_cost_tests.rs, grovedb/src/batch/worst_case_cost_tests.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/visualize.rs, merk/src/merk/mod.rs, merk/src/proofs/chunk.rs, merk/src/proofs/query/mod.rs, merk/src/test_utils/mod.rs, merk/src/tree/commit.rs, merk/src/tree/mod.rs, merk/src/tree/ops.rs, merk/src/tree/walk/mod.rs, storage/src/rocksdb_storage/storage_context/context_batch_tx.rs, storage/src/rocksdb_storage/tests.rs
A more advanced deletion mechanism.
=> feat: advanced deletion

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This should help to make PRs/issues more consistent from all contributors by starting all new issues/PRs with a template. This also aligns with the template used in other Dash repos (platform, tenderdash, mobile, etc.).
Added a PR template (this PR is an example of the format) and unique issue templates for both bug and feature request issues. The issue templates auto-assign the bug or enhancement label.
Same templates used on many other Dash repos.
N/A
=> chore: add standard templates for PRs and issues

grovedb/src/error.rs, grovedb/src/operations/get.rs, grovedb/src/util.rs
=> fix: not finding parent merks no longer a corruption error

grovedb/src/error.rs, grovedb/src/lib.rs, grovedb/src/operations/get.rs, grovedb/src/util.rs
=> fix: error when parent path doesn't exist

grovedb/src/error.rs, grovedb/src/estimated_costs/worst_case_costs.rs, grovedb/src/operations/delete.rs, merk/src/estimated_costs/worst_case_costs.rs, merk/src/merk/defaults.rs, merk/src/merk/mod.rs, storage/src/rocksdb_storage/storage_context/raw_iterator.rs
=> Feat: delete operations up tree while empty

.github/workflows/grovedb.yml, .github/workflows/nodejs.yml, .github/workflows/release.yml, grovedb/src/batch/batch_structure.rs, grovedb/src/batch/estimated_costs/average_case_costs.rs, grovedb/src/batch/estimated_costs/worst_case_costs.rs, grovedb/src/batch/mod.rs, grovedb/src/estimated_costs/average_case_costs.rs, grovedb/src/estimated_costs/worst_case_costs.rs, grovedb/src/operations/delete.rs, grovedb/src/operations/get.rs, grovedb/src/operations/insert.rs, grovedb/src/subtree.rs, grovedb/src/visualize.rs, merk/src/estimated_costs/average_case_costs.rs, merk/src/estimated_costs/mod.rs, merk/src/estimated_costs/worst_case_costs.rs, merk/src/merk/mod.rs, merk/src/tree/kv.rs, merk/src/tree/link.rs, node-grove/src/converter.rs, rust-toolchain.toml
Sum items were previously on Vecs and stored as such. They are now directly on i64s which reduces sizes by 1 byte, and make the interface cleaner for clients of the library.
=> feat: sum Items with i64s

grovedb/src/batch/options.rs, grovedb/src/operations/delete.rs
Small fix to give better deletion options.
=> refactor: better deletion options

grovedb/src/operations/get/query.rs, grovedb/src/query_result_type.rs, merk/src/proofs/query/mod.rs
Sometimes you might want to query keys and know which ones are missing, a new method in this PR allows for that.
=> feat: query raw keys new function that returns None when absent

grovedb/Cargo.toml, grovedb/src/element/mod.rs, grovedb/src/element/query.rs
The verification feature broke after a recent pr, this fixes it.
=> fix: update verification feature

grovedb/src/element/helpers.rs, grovedb/src/element/query.rs, grovedb/src/operations/get/query.rs, grovedb/src/query/mod.rs, grovedb/src/query_result_type.rs, grovedb/src/reference_path.rs, grovedb/src/tests/query_tests.rs, merk/src/error.rs, merk/src/proofs/query/mod.rs, node-grove/src/lib.rs
This allows us to get the path key option<element> for various queries.
It sometimes is vital information to know if something was absent and this PR enables easily checking that.
=> feat: advanced queries for optional non existent values

README.md, grovedb/src/element/query.rs, grovedb/src/operations/get/query.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/query_result_type.rs, grovedb/src/tests/common.rs, grovedb/src/tests/mod.rs, grovedb/src/tests/query_tests.rs, grovedb/src/tests/sum_tree_tests.rs, merk/src/error.rs, merk/src/merk/mod.rs, merk/src/proofs/query/mod.rs, merk/src/proofs/tree.rs, node-grove/index.js, node-grove/src/converter.rs
Subquery paths replace subquery keys to give more power to pathqueries.
=> feat: subquery paths (partial Sam's work)

grovedb/src/batch/key_info.rs, grovedb/src/batch/mod.rs
Small exposure of some PartialEq calls to allow for comparison with slices.
=> chore: PartialEq modification for KeyInfo

grovedb/src/operations/get/mod.rs, grovedb/src/operations/get/query.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/reference_path.rs, grovedb/src/tests/mod.rs, grovedb/src/tests/query_tests.rs, node-grove/src/lib.rs
A little more was needed to support optional merk caching
=> fix: more optional caching

.github/workflows/coverage.yml, README.md
=> feat: add coverage workflow

.github/workflows/coverage.yml, README.md
* add coverage workflow
* wip
* add coverage badge to readme
=> feat: add coverage workflow (#224)

grovedb/src/operations/get/query.rs, merk/src/proofs/query/query_item/intersect2.rs, merk/src/proofs/query/query_item/mod.rs
Adds more tests and comments for range sets.
=> feat: query intersect fixes

grovedb/src/lib.rs
=> feat: better error message

grovedb/src/batch/batch_structure.rs, grovedb/src/batch/estimated_costs/average_case_costs.rs, grovedb/src/batch/estimated_costs/worst_case_costs.rs, grovedb/src/batch/mod.rs, grovedb/src/estimated_costs/average_case_costs.rs, grovedb/src/estimated_costs/worst_case_costs.rs, merk/src/estimated_costs/mod.rs, merk/src/proofs/query/insert.rs, merk/src/proofs/query/merge.rs
We sometimes want to pay only for the replacement of bytes for a part of an item in estimated costs.
Added the ability to say that we are patching an item, and get the correct estimated costs. This has no effect outside of estimated and max costs.
=> feat: patching estimated costs

grovedb/src/element/helpers.rs, grovedb/src/error.rs, grovedb/src/operations.rs, grovedb/src/operations/get/query.rs, grovedb/src/operations/proof.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/query/mod.rs, grovedb/src/tests/sum_tree_tests.rs, merk/src/proofs/query/mod.rs, merk/src/proofs/query/verify.rs
Just a few helpers for path queries.
=> feat: path query helpers

grovedb/src/element/get.rs, grovedb/src/element/insert.rs, grovedb/src/operations/get/mod.rs, grovedb/src/operations/insert/mod.rs
Only update a value if it is different from what already existed or if it is new.
=> Feat: insert if different

grovedb/src/query_result_type.rs
Small convenience method that retries keys from a result
=> feat: to keys for QueryResultElements

adr/README.md
Add a new directory for architectural decision records
=> improve: add adr section to grovedb

adr/README.md, adr/merk-proofs.md
A document describing how Merk proofs work 
=> improve: merk proofs adr

grovedb/src/operations/proof/generate.rs, grovedb/src/tests/query_tests.rs, merk/src/proofs/query/mod.rs, merk/src/proofs/query/verify.rs
Allow verbose proof generation to work on path queries with limits. 
Just removed the constraint checking code
=> feat: remove verbose limit restriction

grovedb/src/operations/proof/generate.rs, grovedb/src/tests/query_tests.rs
=> feat: remove unnecessary comments from #251 

adr/grovedb-structure.md, adr/query-system.md
Adds document to describe the grovedb tree structure
Adds document to describe the grovedb query system
=> improv: add more adr documents

adr/README.md, adr/versioning.md
ADR describing elements and proof versioning. 
=> improv: versioning adr

grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/versioning.rs
Small PR to fix some minor issues in versioning PR.
=> fix: small versioning fixes

.gitignore, tutorials/Cargo.toml, tutorials/README.md, tutorials/src/bin/delete.rs, tutorials/src/bin/insert.rs, tutorials/src/bin/open.rs, tutorials/src/bin/proofs.rs, tutorials/src/bin/query-complex.rs, tutorials/src/bin/query-simple.rs, tutorials/src/main.rs
=> add tutorials

.gitignore, grovedb/src/batch/mod.rs, grovedb/src/element/mod.rs, grovedb/src/error.rs, grovedb/src/lib.rs, grovedb/src/operations.rs, grovedb/src/operations/delete/mod.rs, grovedb/src/operations/get/mod.rs, grovedb/src/operations/get/query.rs, grovedb/src/operations/insert/mod.rs, grovedb/src/operations/proof/generate.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/query/mod.rs, grovedb/src/query_result_type.rs, grovedb/src/reference_path.rs, path/src/subtree_path.rs, tutorials/Cargo.toml, tutorials/README.md, tutorials/src/bin/delete.rs, tutorials/src/bin/insert.rs, tutorials/src/bin/open.rs, tutorials/src/bin/proofs.rs, tutorials/src/bin/query-complex.rs, tutorials/src/bin/query-simple.rs, tutorials/src/main.rs
Add more documentations + Tutorials from @pauldelucia and @thephez 
=> improv: docs

grovedb/Cargo.toml, grovedb/src/batch/mod.rs, grovedb/src/batch/mode.rs, grovedb/src/lib.rs, grovedb/src/operations/delete/average_case.rs, grovedb/src/operations/delete/mod.rs, grovedb/src/operations/get/mod.rs, node-grove/Cargo.toml
Our API is too broad by default, estimated costs is a niche feature thus it deserves a feature flag
=> fix: estimated costs feature gate

grovedb/src/batch/mod.rs, grovedb/src/lib.rs
Improve verify grovedb to check the value_hash consistency of Element::Item
=> feat: Improve verify grovedb + better debug statements

grovedb/src/batch/mod.rs
Update the Ord implementation of Op to take into account new types 
=> fix: op ord implemenation

grovedb/src/batch/mod.rs, grovedb/src/element/mod.rs, grovedb/src/tests/query_tests.rs, grovedb/src/visualize.rs
To find sources of non-determinism in drive we need to see values that updated with grovedb operations as well
- print Element debug with GroveDbOp
- add flags to element debug
Display GroveDbOp outputs
None
=> chore: debug for op value and flags

grovedb/Cargo.toml, grovedb/src/element/mod.rs, grovedb/src/reference_path.rs
Element could not be debugged if using the verify feature.
Element can now be debugged using the verify feature. If visualize feature is also enabled the debug will be pretty.
Not a breaking change
=> fix: element verify debug

grovedb/src/debugger.rs
=> fix visualizer files placed on stack

grovedbg-types/Cargo.toml
=> chore: update grovedbg-types manifest

grovedb/Cargo.toml, merk/Cargo.toml, node-grove/Cargo.toml
=> fix: grovedb-version dep

grovedb/src/lib.rs, grovedb/src/tests/mod.rs
New flag enables an additional check of references integrity
=> feat: verify_grovedb with references

grovedb/src/operations/proof/mod.rs, grovedb/src/operations/proof/verify.rs, grovedb/src/query/mod.rs, grovedb/src/tests/query_tests.rs, merk/src/proofs/query/verify.rs
There was no issue in grovedb, however there was an issue in drive that warranted an investigation. These tests were made and should be kept.
Added tests.
Small refactoring.
Added convenience methods.
=> test: query asc desc with subquery limit

costs/Cargo.toml, grovedb-epoch-based-storage-flags/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedbg-types/Cargo.toml, merk/Cargo.toml, node-grove/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, visualize/Cargo.toml
Updated to v2.
Added MIT license information to new crates.
=> chore: bump to version 2.0.0

costs/Cargo.toml, grovedb-epoch-based-storage-flags/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedbg-types/Cargo.toml, merk/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, visualize/Cargo.toml
=> chore: version bump to v2.0.1

costs/Cargo.toml, grovedb-epoch-based-storage-flags/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedbg-types/Cargo.toml, merk/Cargo.toml, node-grove/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, visualize/Cargo.toml
We had previously bumped the version, but we hadn't done this properly
=> chore: bump version to 2.0.3

grovedb/build.rs
Update grovedbg dependency
Updated grovedbg dependency with checksum
Tested manually
=> chore: bump grovedbg v1.2.0

costs/Cargo.toml, grovedb-epoch-based-storage-flags/Cargo.toml, grovedb-version/Cargo.toml, grovedb/Cargo.toml, grovedbg-types/Cargo.toml, merk/Cargo.toml, node-grove/Cargo.toml, path/Cargo.toml, storage/Cargo.toml, visualize/Cargo.toml
=> chore: update to version 2.2.0

grovedb/src/debugger.rs, grovedb/src/element/get.rs, grovedb/src/element/insert.rs, grovedb/src/element/query.rs, grovedb/src/error.rs, grovedb/src/operations/get/mod.rs, grovedb/src/tests/mod.rs, grovedbg-types/src/lib.rs
1. Fix compilation issues
2. Append error context where applicable as an Error's functionality 
=> feat: append error context
